services:
  - type: web
    name: library-management
    env: java
    rootDir: library-Backend
    healthCheckPath: /actuator/health
    buildCommand: chmod +x mvnw && ./mvnw clean package -DskipTests
    startCommand: java -jar target/library-management-1.0.0.jar
    envVars:
      - key: JAVA_VERSION
        value: 17
      - key: SPRING_PROFILES_ACTIVE
        value: cloud
